name: Tests

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    run-backend-tests:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v3

            # Set up Node.js environment
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22" # Specify your Node.js version

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Run nx test for the backend project
            - name: Run tests
              run: npm run test